export const userMock = {
  id: 0,
  title: "Marcelo",
  image: "/mc.jpg",
  data: "marcelo.coldibelli@gmail.com",
  highlighted: "",
}

export const userMocksGroup = [
  {
    id: 0,
    title: "Marcelo",
    image: "/mc.jpg",
    data: "Purchased",
    highlighted: "Iphone 14",
  },
  {
    id: 1,
    title: "Arthur",
    image: "/profile pictures/arthur.jpg",
    data: "Purchased",
    highlighted: "Book 1984",
  },
  {
    id: 2,
    title: "Anastasia",
    image: "/profile pictures/anastasia.jpg",
    data: "Purchased",
    highlighted: "MacBook Pro",
  },
  {
    id: 3,
    title: "Christina",
    image: "/profile pictures/christina.jpg",
    data: "Purchased",
    highlighted: "Samsung Galaxy S21",
  },
  {
    id: 4,
    title: "Darina",
    image: "/profile pictures/darina.jpg",
    data: "Purchased",
    highlighted: "Dell XPS 13",
  },
  {
    id: 5,
    title: "Joseph",
    image: "/profile pictures/joseph.jpg",
    data: "Purchased",
    highlighted: "Google Pixel 6",
  },
  {
    id: 6,
    title: "RON",
    image: "/profile pictureS/ron.jpg",
    data: "Purchased",
    highlighted: "Surface Pro 7",
  },
  {
    id: 7,
    title: "Sorrah",
    image: "/profile pictures/sorrah.jpg",
    data: "Purchased",
    highlighted: "Kindle Paperwhite",
  },
  {
    id: 8,
    title: "Spencer",
    image: "/profile pictures/spencer.jpg",
    data: "Purchased",
    highlighted: "PlayStation 5",
  },
  {
    id: 9,
    title: "Vaz",
    image: "/profile pictures/Vaz.jpg",
    data: "Purchased",
    highlighted: "Nintendo Switch",
  },
];
